### ISSUE TITLE
syncmanager stuck with Please wait... and never recovers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1158]
This happens whenever Beset is rebooting the site. The sync manager never recovers from it.
It should try to load the app for a while and if that does not work it should give an error and the option to reload.

**Comment by urapadmin** [comment]
When that happens the app is already loaded and active. What does not work is the api call or some such. But that also does not come back with an error. After the quite a while it takes the sync manager finally receives the data and everything is fine. So the Please wait... looks static but there is actually something going on.

**Comment by urapadmin** [comment]
### kiosk 0.12
I have tried a few improvements in the sync manager for 0.12. Let's see if that already makes a difference. Presumably this is not the end of the affair. 
One issue I saw was that kioskStartWhenReady was not availabe when the sync manager tried to start. It will try now as long as it takes for that part of kiosk to load.

**Comment by lbestock** [comment]
Is there a specific way to test this?

**Comment by urapadmin** [comment]
no. If it doesn‘t happen too often (I still see it after Beset restarts a project), we just close this one day.

**Comment by urapadmin** [comment]
yes, sync manager = field manager = workstation manager
the thingy changes its name frequently (I plan to change it again soon so that we all get more confused).

**Comment by urapadmin** [comment]
okay,that's good enough for me then.
