### ISSUE TITLE
kiosk housekeeping warning returns when not appropriate

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/kiosk#1287]
The warning to do housekeeping after restore comes back like a bad penny. I restored. I got the nice warning message to run housekeeping. I ran housekeeping. I went to the file repository, and the message to run housekeeping was still there. I clicked it closed. I went to administration and the warning was back again. It should disappear once housekeeping has been run and not return.
![image](https://user-images.githubusercontent.com/49291909/149240276-01f57313-47c2-4c3b-beab-1f81d0c7577b.png)

**Comment by urapadmin** [comment]
Ja, the messaging system still has this strange delay. See #1009, which I will reopen, too.

**Comment by urapadmin** [comment]
I made a new ticket for the fix: 
- [ ] #1347 

This here is the testing ticket

**Comment by urapadmin** [comment]
### kiosk 0.14.4
- this should be working now

**Comment by urapadmin** [comment]
close #1009 when closing this here.

**Comment by luizaogs** [comment]
Was going to test this but I'm scared of breaking things at this point :) Is the backup destination the path that's already there, or would I have to change it? The wiki implied the former but I thought I would check.

**Comment by urapadmin** [comment]
I have just tried this myself because of #574 and currently one does not get the housekeeping message at all. So please wait with further tests until I have tackled #574

**Comment by urapadmin** [comment]
### kiosk 0.15.2
Now it should work.

**Comment by luizaogs** [comment]
Should it disappear by itself once housekeeping has been run, or should I have to click on it?

**Comment by urapadmin** [comment]
and that is what it should do.
It is really just a reminding message that's fired after a restore has happened. All these system messages need to be closed by someone.

**Comment by luizaogs** [comment]
Good!
