### ISSUE TITLE
urap ceramics deletion issues

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/kiosk#1296]
Deletion issues stemming from #1257.

Using the FM menu to delete the image results in the same issue reported for su ceramics in #1289 -- empty image container remains in gallery but image is gone. Trash button works properly.

**Comment by luizaogs** [comment]
Ah, things get more exciting. If I add an image from the gallery and then use the FM menu to delete it, it is also deleted from the gallery but the old identifier remains (the ceramic number does not stay as an identifier).

**Comment by lbestock** [comment]
Not quite sure if a different image container issue with URAP ceramics belongs here, too? https://github.com/urapadmin/kiosk/issues/1301#issuecomment-1013763963

(A 3 is that the whole list of image containers goes blank temporarily.)

**Comment by urapadmin** [comment]
> Not quite sure if a different image container issue with URAP ceramics belongs here, too? [#1301 (comment)](https://github.com/urapadmin/kiosk/issues/1301#issuecomment-1013763963)
> 
> (I got an error 3 in URAP ceramics, while I had a bunch of other apps running. I did not get the error when I closed the other apps. A 3 is that the whole list of image containers goes blank temporarily.)

we ignore that one for the time being until it is reported more often

**Comment by urapadmin** [comment]
### @test 11.6.20
so far the latest image container handling was not fully applied to this container. It is special in the way that it is within a popup, so pretty possible that things don't work as well in this scenario. I have also added the latest "please wait" panel from #1293 but only for the portal.

So this needs a thorough test again from all of you.

**Comment by luizaogs** [comment]
All is working for me.

**Comment by urapadmin** [comment]
@lbestock, @mcornacchia25:
I would like to have you confirm this before we clsoe it.

**Comment by lbestock** [comment]
I could not remember how to get back to URAP pottery processing to test this. Needs documentation. @mcornacchia25, when you come to test this, the trick is to go into configuration, modules, ceramic_module, and reset it to pottery_processing.

**Comment by lbestock** [comment]
This is good for me!

**Comment by mcornacchia25** [comment]
Everything looks good to me.
