### ISSUE TITLE
file repository hiccup with a double-assigned context

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/kiosk#1318]
An image added through file import shows up as having the same context applied twice in the overview view of the File Repository. It likewise has been sent twice as a dayplan to the workstation. But it doesn't have the designation twice when I click on the "edit file". It should not be possible for it to be there twice in the same place, no?
![image](https://user-images.githubusercontent.com/49291909/150653489-27724288-16c8-42f6-9833-c3538c441b4b.png)

![image](https://user-images.githubusercontent.com/49291909/150653476-16e44a5d-9b02-478e-b410-75c243d24304.png)

![image](https://user-images.githubusercontent.com/49291909/150653501-ec22343d-0d73-40f9-8a54-565f263710d6.png)

I then went back into the File Repository and clicked to remove that context, and it seems to have removed both instances with one click.

**Comment by lbestock** [comment]
I am able to repeat this. I get there by assigning the context in "edit file" and clicking the little check button to accept my edits twice quickly in succession. A normal double click.

**Comment by urapadmin** [comment]
### @test kiosk 0.15.1
hm. That's a general JavaScript issue, I learned. A double click is not only recognized as a double click and so two clicks AND a double click are issued. That's a bit dumb. So I have to disable buttons manually after they have been clicked. Always! IN all dialogs! 

@arch-kiosk/test: 
I just care for this one here, but it is good to know for testers that when dealing with browser UIs double clicking is something worth testing.

**Comment by luizaogs** [comment]
This seems good now!
