### ISSUE TITLE
creating a locus with the plus button in the locus layout must go back to observations tab

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1328]
If one is in relations after creating a new locus things look strange. 
Also QC does not run.

**Comment by urapadmin** [comment]
### #11.6.25
- fixed

**Comment by luizaogs** [comment]
If I do this in the locus layout form I get the following error (but the locus is created normally).

<img width="1028" alt="Screen Shot 2022-01-31 at 4 40 27 PM" src="https://user-images.githubusercontent.com/67970402/151885053-379abd98-d737-40d0-bf33-cf0997d8ec04.png">

**Comment by luizaogs** [comment]
The rest is working.

**Comment by urapadmin** [comment]
oh, good you thought of that. Totally slipped my mind that the code is shared between those two.

**Comment by urapadmin** [comment]
### @test 11.6.26
fixed

**Comment by lbestock** [comment]
But you have not released 11.6.26?

**Comment by urapadmin** [comment]
no, not for a single ticket. I am waiting for you guys to finish the tests.

**Comment by urapadmin** [comment]
#### v12
now you can test this last one in version 12. 
@arch-kiosk/test: Note that I no brake with the tradition to name the files something like pvd2021. From now on it is pvd_recording.fmp12. No years anymore.

**Comment by lbestock** [comment]
Works.
