### ISSUE TITLE
file import: a space in the identifier should NOT be interpreted as separator when using QR Code filter

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1338]
This space also causes problems with the QR code, saying that the identifier "Meghan" is not recognized, but otherwise the QR code seems to be working. 

_Originally posted by @mcornacchia25 in https://github.com/arch-kiosk/kiosk/issues/903#issuecomment-1030503413_

**Comment by urapadmin** [comment]
### @test kiosk 0.14.2
should be fixed

**Comment by luizaogs** [comment]
Was going to test this but MCP is not up, sad face.

**Comment by luizaogs** [comment]
Oh wait, export worked so I guess it's a fake warning? Relevant for #1009?

**Comment by luizaogs** [comment]
The QR code with an identifier with a space (LA Test) worked just fine.

**Comment by urapadmin** [comment]
> Oh wait, export worked so I guess it's a fake warning? Relevant for #1009?

ja, yesterday's update has screwed up poor Beset.
