### ISSUE TITLE
file import: adding a candid with a description does not work

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1339]
The wiki also mentions that you should be able to only check the description box to add a candid with a description, but when I tried to do that, I got this error:

<img width="775" alt="Screen Shot 2022-02-04 at 9 28 44 PM" src="https://user-images.githubusercontent.com/96021337/152625540-cb3c296e-908a-478b-862a-aa94288f0484.png">

_Originally posted by @mcornacchia25 in https://github.com/arch-kiosk/kiosk/issues/903#issuecomment-1030503413_

**Comment by urapadmin** [comment]
here I am not sure how exactly you set up the import. If you import a candid you would first uncheck "import only files with context". I suppose you did that. Can you show me the rest of your settings?

**Comment by mcornacchia25** [comment]
I forgot what my exact settings were, so I tried again with these settings which worked. I think you were right that I must have had the first box checked. 

<img width="764" alt="Screen Shot 2022-02-05 at 1 35 14 PM" src="https://user-images.githubusercontent.com/96021337/152654447-f16f10e5-6391-4ba5-a173-e8a8d185ff2f.png">

A slight confusion with the title of the categories is that even when I don't want to add a context, I must select the "context from operating system file" option. Without that checked it doesn't work. Maybe change it to something like "context/description from operating system file" to make it more clear? But either way, I think what I initially thought was a bug was just error on my side.

**Comment by urapadmin** [comment]
I can think of something else: Is it possible that you did not check the box but instead had the qr code detection on and it did detect a qr code in that image?

**Comment by mcornacchia25** [comment]
That seems very unlikely unless the QR code detection is really inaccurate. I looked back through the images I was testing with and none of them had anything that might look at all like a QR code. I also tried uploading a QR code I generate for google.com with the QR code filter on and it just took the file name as the description

**Comment by urapadmin** [comment]
okay, if there were no QR Codes in there, then my idea is mush.
Let's close this, I'd say?

**Comment by mcornacchia25** [comment]
Sounds good to me
