### ISSUE TITLE
filemaker: Barcode Creator is commercial and not open source. 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1340]
Barcode Creator cannot be part of the GitHub Repository, which means that project won't have access to the QR Code feature unless they pay their own license of Barcode Creator. As far as I can see all Brown projects will be alright.

**Comment by urapadmin** [comment]
[Barcode Creator Site License.txt](https://github.com/arch-kiosk/kiosk/files/8009045/Barcode.Creator.Site.License.txt)

**Comment by urapadmin** [comment]
This means I have to take that part of the source code out of the published fmp12 file. In which case it really makes zero sense to manage the filemaker recording as a repository at all. But I also have to make sure that no fragment of the fmp12 file is somewhere in the kiosk repository.

**Comment by urapadmin** [comment]
on looking for a non-commercial solution I found this:
[qrWebViewer.fmp12.zip](https://github.com/arch-kiosk/kiosk/files/8009090/qrWebViewer.fmp12.zip)
coming out of [[https://community.claris.com/en/s/question/0D50H00006dsgcg/recommendations-for-qrcode-generation-in-fmp]]. But it might not work on FM GO. We'll see.

**Comment by urapadmin** [comment]
### recording V12
for the time being we will just erase the Barcode Creater parts from the published version of the recording. I have put code in place that deals with its absence.

**Comment by urapadmin** [comment]
### test v12
Please test that qr codes are still working (it is enough to test this in one of the layouts only)

**Comment by urapadmin** [comment]
>     * the fmp12 demo above is temporarily built into the current v12 filemaker file ot see if it works on fm go

surprise, surprise, it does not work on fm go

**Comment by luizaogs** [comment]
So we shouldn't test this, then?

**Comment by urapadmin** [comment]
just a quick look if the qr code generation still works on PVD would do. Just don't close this ticket afterwards.

**Comment by lbestock** [comment]
It appears to work for me.

**Comment by urapadmin** [comment]
that's enough for me then

**Comment by urapadmin** [comment]
I have closed it in testing but leave it open because I still have some cleaning up to do because of it.

**Comment by urapadmin** [comment]
we have a neutral recording version now that does not use the Barcode Creater and I have replaced all filemaker databases in the kiosk repository with the new neutral database: recording_v12_template.fmp12. That would be the one to publish on GitHub when we roll out.
