### ISSUE TITLE
trigger a server restart manually 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1346]
There should be a simple button in the admin pane that triggers a server restart.

**Comment by urapadmin** [comment]
### @test kiosk 0.15
- new feature implemented: There is a "restart server" button now on the admin page that should trigger a restart. You can see that the restart actually happened  because the server will be pretty unresponsive for a while.

**Comment by luizaogs** [comment]
Hm I already see the "restart server" button in admin, but should I not test it before 0.15?

**Comment by urapadmin** [comment]
I was incoherent with versioning. Since it is a new feature I should have gone up to 0.15. But I didn't. We are on 0.14.5 and you may hit the button.

**Comment by luizaogs** [comment]
Woops, I tried this and got the following. Do I need a specific permission for this or should it have worked?

<img width="1512" alt="Screen Shot 2022-02-12 at 8 06 04 AM" src="https://user-images.githubusercontent.com/67970402/153714561-e2f53e08-9921-48bc-b493-e7a98ff5f0f5.png">

**Comment by urapadmin** [comment]
I get this, too. The server does restart nonetheless. The issue might be that the server starts abruptly and so the response does not come through. Since it is an admin feature, I could live with it.
Did it restart, though? You would have a long time until your next response and you'd get a new yellow  system information messages with the PID and TID.

**Comment by luizaogs** [comment]
It don't think it restarted? I can get back to the field manager immediately, and do not get a new system information message.

**Comment by urapadmin** [comment]
> I don't think it restarted? I can get back to the field manager immediately, and do not get a new system information message.

then it did not, indeed.

**Comment by urapadmin** [comment]
It seems this was just a missing privilege on Windows, not a bug. I have applied one and you may try again.
I at least did not get another authorization issue and the server clearly restarted.

**Comment by lbestock** [comment]
![9F3EF2EF-1BF5-41B4-B8A1-CA9CB1C4E949](https://user-images.githubusercontent.com/49291909/153738344-9cb0f528-1bd2-4cc9-9e60-41e58bacf24f.jpeg)
I get an error, but then if I go back in it does appear to be too busy to pay attention to me for 10 seconds or so, and I get the PIS message.

**Comment by urapadmin** [comment]
that is exactly what should happen

**Comment by luizaogs** [comment]
Worked for me, too.
