### ISSUE TITLE
💡 GITHUB TIP: Use involves:@me to see all your issues 💡

### ISSUE THREAD

**Issue by PeterDeathBredon** [arch-kiosk/kiosk#1359]
:octocat: It works in project boards as well!

⚡  some more detailed description of how filtering your issues works can be found in the wiki here: [how_github_connects_you_to_an_issue](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=the_3_confusing_ways_you_get_connected_to_a_github_ticket#how_github_connects_you_to_an_issue)
\\
📖  And if you want even more details on how to filter issues, look at the really readable [GitHub documentation on the topic](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests)

**Comment by urapadmin** [comment]
# Use involves:@me to see all your issues

😞  It DOES NOT work in project boards, though.

⚡  some more detailed description of how filtering your issues works can be found in the wiki here: [how_github_connects_you_to_an_issue](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=the_3_confusing_ways_you_get_connected_to_a_github_ticket#how_github_connects_you_to_an_issue)
\\
📖  And if you want even more details on how to filter issues, look at the really readable [GitHub documentation on the topic](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests)

**Comment by urapadmin** [comment]
### refer to tickets by using a new line and a dash
like so:
- #974 
- #765 

if you want a ticket being tracked please do exactly the same thing but in the body comment of the ticket (that's the first comment).

**Comment by urapadmin** [comment]
we have some general knowledge on how we use GitHub and on how it works in the wiki : [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:github_issue_tracking#github_messaging](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:github_issue_tracking#github_messaging).

The latest I learned is:
[](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:github_issue_tracking#github_messaging)

### github messaging

GitHub sends an email to users who are in some way or the other assigned to a ticket. But it depends on how they subscribe and how they are assigned:

-  assignees get an update on all changes to a ticket
-  users who are just mentioned (with @) get an email only on that comment. Subsequent changes to the issue do not lead to a new email.
-  users who have commented themselves on a ticket are associated and do get an email on all updates.

**Comment by urapadmin** [comment]
@arch-kiosk/test:
no "back to developer" pane anymore in the testing project. Please just remove a ticket that has to go back to the developer from the project:
![image](https://user-images.githubusercontent.com/38838314/175523037-8c2f3f14-dee2-4622-8422-4e777c329dc7.png)
