### ISSUE TITLE
file export - exported_filename column empty despite "render descriptive filenames"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1362]
@luizaogs reported: 
I am first testing this with the "render descriptive filenames" option. The wiki says that, in this case, the filename column should still have the original file repository name, which seems to be the case. But it also says that the exported_filename column should show the descriptive file name, which is not the case at the moment -- the column is empty. (Though there is a description column, and that is not empty.)

<img width="1512" alt="Screen Shot 2022-02-12 at 11 08 42 PM" src="https://user-images.githubusercontent.com/67970402/153739617-04e030cc-fe1b-4a8e-97cd-9fd18b8958e8.png">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/kiosk/issues/438#issuecomment-1037783565_

**Comment by urapadmin** [comment]
that happens for the same reason as #1364: There are not File Picking rules for this workstation (Workstation type for those file picking rules should be FileExportWorkstation). 
If a file does not get exported due to file picking rules it will not have an entry in the export_filename column

**Comment by urapadmin** [comment]
### kiosk v0.15 
is out and you may close this if having the right file picking rules solves the issue

**Comment by luizaogs** [comment]
Can't do this yet because of #1363

**Comment by luizaogs** [comment]
This isn't working yet -- the exported_filename column is still empty, even though I exported using the "render descriptive filenames" option.

**Comment by luizaogs** [comment]
That was a total lie.

**Comment by luizaogs** [comment]
(I forgot that I needed to scroll through the spreadsheet to find the damn images I actually exported. Wow. My brain today.)

**Comment by urapadmin** [comment]
🥴 Ha. There is a :woozy_face!

**Comment by luizaogs** [comment]
🤡 -> me
