### ISSUE TITLE
file export: file repository files don't get included

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1364]
@luizaogs reported:
Also, a question: this is probably because I am tired but from reading the wiki I am unsure if I should have gotten all of the file repository files in the zip, too, if I checked the "export files from file repository" box. It sounds to me like that should be the case, but I did not get any of those -- only Excel spreadsheets.

_Originally posted by @luizaogs in https://github.com/arch-kiosk/kiosk/issues/438#issuecomment-1037785443_

**Comment by urapadmin** [comment]
see also:
- [ ] #1363

**Comment by urapadmin** [comment]
This is less a bug than a result of missing file picking rules: 
file picking rules have this first attribute "Workstation Type". We have never used it so far because it was always "FileMakerWorkstation" with the recording system. 
But the file export workstation is a different type - for good reasons - and so it needs its own set of file picking rules.

Once implemented #1363 will warn if a file export workstation has NO file picking rules at all and stop (unless files are excluded anyhow).

You should also really use file picking rules to reduce the file size and the number of files drastically in order not to create enormous file sizes.

**Comment by urapadmin** [comment]
I have added a little hint in the wiki to point to the fact that file picking rules need to use "FileExportWorkstation" as workstation type in order to work for the export.

**Comment by luizaogs** [comment]
Right, but if there were no file picking rules then I should have gotten all the files, no? Rather than none of them?

**Comment by urapadmin** [comment]
no, the default is indeed none. I know, we (I) have such a documentation backlog :(

**Comment by urapadmin** [comment]
> Right, but if there were no file picking rules then I should have gotten all the files, no? Rather than none of them?
> 
> Oh wait, I just saw your comment in #1363 about the error keeping files from being exported at all. Never mind.

ja, unfortunately I do mind because at that point I thought it was a bug, indeed. But there is no real bug, it is really only the missing file picking rules. But I am currently working on the warnings in #1363 and the log issue in #1368. Then you may give it all another try.

**Comment by urapadmin** [comment]
### Kiosk v0.15
Now that a few other bugs are fixed that made testing file export impossible, you give it another try.

**Comment by luizaogs** [comment]
Can't do this yet because of #1363

**Comment by luizaogs** [comment]
Yay, works.
