### ISSUE TITLE
file export: When including images the process seems stuck because the percentage display does not go on 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1367]
In the field manager the percentage circle is stuck at about 63% if images are included for the whole process of exporting images - which takes much longer than anything else.

So if images are included the percentage meter should use 50% for the data tables and 50% for the images. 
If images are not included the whole 100% range should be used for data tables.

**Comment by urapadmin** [comment]
### kiosk v0.15
When exporting the percentage circle should move throughout the whole process.

**Comment by urapadmin** [comment]
it's not perfect :o)

**Comment by urapadmin** [comment]
ja, there is still something with the math wrong. I should call in Norah.

**Comment by urapadmin** [comment]
### @test kiosk v0.15.1
- the progress should not hop back anymore

**Comment by luizaogs** [comment]
Not sure if you did call in Norah, but it works now!
