### ISSUE TITLE
file export: descriptive filenames being used when "use unique id as filename" is chosen

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/kiosk#1370]
Well the title is pretty descriptive here, I think. 

Both filenames for the downloaded files and the exported_filename column have the descriptive names when I'm using the settings below: 

<img width="535" alt="Screen Shot 2022-02-13 at 8 08 48 PM" src="https://user-images.githubusercontent.com/67970402/153788146-8efacdac-5550-4ff9-8e54-5e35bcfda894.png">

**Comment by urapadmin** [comment]
again I cannot confirm this. I tried it locally and checked the code: all okay. 
Then I tried it on Beset and it worked there, too.
I get the feeling we have a severe caching issue going on here and so this would be an instance of #1365. But even that does not happen to me on Windows. It is weird. 

I tricked myself a few times by confusing XLSX with CSV. So I was looking at an older CSV although I just took an XLSX out of the ZIP. But that would not explain the wrong filenames for the images themselves. I am a bit at a loss here.

**Comment by luizaogs** [comment]
Argh. I will try it again (a good break from the German I've been reading all day, which has given me a migraine. No offense intended).

**Comment by urapadmin** [comment]
I just saw it, too, but now I wonder if we got into each others way.

**Comment by luizaogs** [comment]
Oh sorry, I thought you were done!

**Comment by urapadmin** [comment]
ja, we got into each other's way. My test worked fine then.

**Comment by urapadmin** [comment]
(you know I would always help you with some particularly awkward German passages, right?)

**Comment by luizaogs** [comment]
Ok, this worked now. But I just find it hard to believe that I messed it up so many times yesterday (though maybe I should not) and the Excel / CSV mess in #1365 suggests to me that something is going on, at least locally on my end.

**Comment by luizaogs** [comment]
> (you know I would always help you with some particularly awkward German passages, right?)

Ha, thank you. But it's a 450 page book, of which not even half is relevant, so I mostly skim it while crying.

**Comment by urapadmin** [comment]
that would be a bit lengthy and dry, I guess.

**Comment by luizaogs** [comment]
It's also an excavation report so, yes, "dry" is a kind way to put it.

**Comment by urapadmin** [comment]
no, I don't believe that you messed this up either. I'll close the two issues and open a new one that addresses this as a cache issue of the file manager, okay?

**Comment by luizaogs** [comment]
ja :)

**Comment by urapadmin** [comment]
oh. Presumably one of those instances where "Germans publish data and no interpretation".

**Comment by luizaogs** [comment]
that would also be a ja...

**Comment by urapadmin** [comment]
very affirmative end to this flaky ticket for me
