### ISSUE TITLE
file export: use workstation's description as filename

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1373]
an idea to quickly address some issues raised in #1361: 
Just using the export workstation's description as the filename for the export.

**Comment by urapadmin** [comment]
### kiosk v0.15.1
- the exported zip file in the file manager will now have the workstation's description as its name. 
- Should the workstation's description contain illegal characters for filenames, the name will be slightly altered to be compliant.ß

**Comment by luizaogs** [comment]
Works.
