### ISSUE TITLE
restore failed?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/kiosk#1382]
Hmpf. Not sure if I did something wrong. As admin I should be able to do it, no?

<img width="1512" alt="Screen Shot 2022-02-17 at 2 37 48 PM" src="https://user-images.githubusercontent.com/67970402/154566784-983ea104-5b84-4930-9598-70509951016e.png">

**Comment by urapadmin** [comment]
we did it at the same time, it seems: #1287 , #574

**Comment by urapadmin** [comment]
### @test kiosk v0.15.2
No, that was not the correct message. The correct message should appear after the restart and looks like this:
![image](https://user-images.githubusercontent.com/38838314/154620449-566b127c-bb5a-4fb3-996e-b0b7c8070559.png)

**Comment by luizaogs** [comment]
Yup.
