### ISSUE TITLE
export data to Excel / CSV

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#438]
The first step would be to just export all tables for a project, much like Parker's system does. One important step towards that was introducing the arch_context everywhere. The export should use some kind of dsd-view that allows to hide certain technical fields from the export.   

In a second step we could also export (and rename) images connected to the excel records. Also something, Parker's system did. That way we would give people the chance to get everything out of the system and that should reassure them that they have full control.

### tracked issues 
(I do that up here because it only works in the body of an issue):
- [x] #1362 
- [x] #1363
- [x] #1364 
- [x] #1365

**Comment by urapadmin** [comment]
Should #49 be done first so that images show a proper arch_context?

**Comment by urapadmin** [comment]
- [ ] create FileExportWorkstation
- [ ] Create/Edit Dialog
- [ ] action dialog
- [ ] Define export cycle for it
- [ ] export of data
- [ ] export of files
- [ ] upload

**Comment by urapadmin** [comment]
@test kiosk 0.13
There is so much to test.

**Comment by urapadmin** [comment]
there is a documentation for users now: [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:user_manual:file_export](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:user_manual:file_export)

**Comment by luizaogs** [comment]
I am first testing this with the "render descriptive filenames" option. The wiki says that, in this case, the filename column should still have the original file repository name, which seems to be the case. But it also says that the exported_filename column should show the descriptive file name, which is not the case at the moment -- the column is empty. (Though there is a description column, and that is not empty.)

<img width="1512" alt="Screen Shot 2022-02-12 at 11 08 42 PM" src="https://user-images.githubusercontent.com/67970402/153739617-04e030cc-fe1b-4a8e-97cd-9fd18b8958e8.png">

**Comment by luizaogs** [comment]
Also, a question: this is probably because I am tired but from reading the wiki I am unsure i I should have gotten all of the file repository files in the zip, too, if I checked the "export files from file repository" box. It sounds to me like that should be the case, but I did not get any of those -- only Excel spreadsheets.

**Comment by luizaogs** [comment]
Just to be clear, these are the settings pertaining to the two comments above: 

<img width="551" alt="Screen Shot 2022-02-12 at 11 14 08 PM" src="https://user-images.githubusercontent.com/67970402/153739714-68575ca4-0ff3-4c6a-acaa-c25687b4c52a.png">

**Comment by luizaogs** [comment]
The inventory spreadsheet is completely empty -- not sure if that should be the case.

**Comment by luizaogs** [comment]
Now I'm testing with the "use unique id as filename" option.

Now the exported_filename column is empty, which is what I expected (should it be there at all, though?). I still do not get actual files from the repository in the zip, however, even if I clicked that option. 

The inventory, tickets, unit_shop, and workflow_requests spreadsheets are all empty here, too.

**Comment by luizaogs** [comment]
Now I'm doing an Excel export but I did not click on the export files from file repository box and indeed do not get files, so I suppose I should have gotten them for the two tests above.

I still get the exported_filename here in the images spreadsheet, not sure if it should be there.

The inventory, tickets, unit_shop, and workflow_requests spreadsheets are all empty here, too.

**Comment by luizaogs** [comment]
Hmm ok lastly I was going to try exporting it all as CSV files, but I got the same Excel sheets again after changing the settings. Not sure if something went wrong with the fork?

<img width="575" alt="Screen Shot 2022-02-12 at 11 41 04 PM" src="https://user-images.githubusercontent.com/67970402/153740500-a29dcd1f-ce05-4c5d-8e3f-648f746c4474.png">

<img width="895" alt="Screen Shot 2022-02-12 at 11 43 19 PM" src="https://user-images.githubusercontent.com/67970402/153740535-fc4f1332-238a-4f3e-9fd1-78d5e294d562.png">

**Comment by luizaogs** [comment]
(Sorry for the zillion comments -- I wasn't sure what was an actual issue and what was not so didn't want to start a bunch of new bogus tickets!)

**Comment by urapadmin** [comment]
> The inventory spreadsheet is completely empty -- not sure if that should be the case.
> 
> The same goes for unit_shop, tickets, and workflow_requests.

If the inventory in the recording is empty then the exported file will have no records, either.
unit_shop is for sure empty, I don't know if you ever have used tickets in PVD but I guess you have not used workflow_requests.
It is debatable if these tables need to be exported at all, but that can be configured per project.

**Comment by urapadmin** [comment]
> Also, a question: this is probably because I am tired but from reading the wiki I am unsure if I should have gotten all of the file repository files in the zip, too, if I checked the "export files from file repository" box. It sounds to me like that should be the case, but I did not get any of those -- only Excel spreadsheets.

see #1364

**Comment by urapadmin** [comment]
> (Sorry for the zillion comments -- I wasn't sure what was an actual issue and what was not so didn't want to start a bunch of new bogus tickets!)

it really is always better to make new and smaller tickets. It is much easier to delete or close a ticket than to dissect it.

**Comment by urapadmin** [comment]
> Hmm ok lastly I was going to try exporting it all as CSV files, but I got the same Excel sheets again after changing the settings. Not sure if something went wrong with the fork?
> 
> <img alt="Screen Shot 2022-02-12 at 11 41 04 PM" width="575" src="https://user-images.githubusercontent.com/67970402/153740500-a29dcd1f-ce05-4c5d-8e3f-648f746c4474.png">
> 
> <img alt="Screen Shot 2022-02-12 at 11 43 19 PM" width="895" src="https://user-images.githubusercontent.com/67970402/153740535-fc4f1332-238a-4f3e-9fd1-78d5e294d562.png">

see #1365

**Comment by urapadmin** [comment]
> > > (Sorry for the zillion comments -- I wasn't sure what was an actual issue and what was not so didn't want to start a bunch of new bogus tickets!)
> > 
> > 
> > it really is always better to make new and smaller tickets. It is much easier to delete or close a ticket than to dissect it.
> 
> Right, sorry.

Gives us the chance to test the tracking feature on github in this issue's body.

**Comment by urapadmin** [comment]
now that all the tracked issues are closed, we could close this. Unless you object.

**Comment by luizaogs** [comment]
Nope.
