### ISSUE TITLE
Upgrade to flask 2: The session cookie will soon be rejected by firefox

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#911]
JavaScript console tells me:
>Cookie “session” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by urapadmin** [comment]
werkzeug seems to have added support for this. But It is up to 2.0.x and I hesitate to just upgrade it. That can lead to a bunch of other issues. Later.

**Comment by urapadmin** [comment]
yes, I accidentally did upgrade to flask 2 on Beset and guess, what? Boom. So this is not so trivial to fix.

**Comment by urapadmin** [comment]
I should do that together with #903

**Comment by urapadmin** [comment]
Problem on Beset is that this needs all projects to migrate to the new kiosk version!

**Comment by urapadmin** [comment]
### @test 0.13.14
see #903 for testing instructions

**Comment by urapadmin** [comment]
the session cookie reacts the same way in kiosk on Flask 1 as on the new Flask 2. It seems, Google and Firefox now do not reject anything any longer but rather issue a warning and set a default. Very confusing and I will just ignore it because it does not look like an issue at this point.

**Comment by lbestock** [comment]
@urapadmin can we close this since we are doing general kiosk testing on #903?

**Comment by urapadmin** [comment]
yup
